### ISSUE TITLE
Sample rate hardcoded?

### ISSUE THREAD

**Issue by everyoneishappy** [vvvv/VL.Audio.GPL#3]
Is there any reason Gist only works when sample rate is set to 44100Hz ?

**Comment by joreg** [comment]
yes, it is indeed hardcoded in the underlying library used: https://github.com/adamstark/Gist

**Comment by bj-rn** [comment]
Just peeked at the code and while I don't really understand C++ that much, from what I can gather the sample rate isn't harcoded. It is passed when instantiating Gist:
https://github.com/adamstark/Gist/blob/d6a921b3cd3a642123767a7c27699ac160fe8fd1/src/Gist.cpp#L29
and can also be set/changed later: 
https://github.com/adamstark/Gist/blob/d6a921b3cd3a642123767a7c27699ac160fe8fd1/src/Gist.cpp#L72

**Comment by joreg** [comment]
confirmed, thanks for digging. the restriction doesn't seem to be in the code of the underlying library indeed. but i just tested again with 48khz and it simply crashes.
