### ISSUE TITLE
New nuget layout does not pickup native DLLs

### ISSUE THREAD

**Issue by mhusinsky** [vvvv/VL.Audio.GPL#4]
the changes in nuget version 1.1.1 seem to break BTrack. it appears to me that the new nuget layout does not pick up the respective native dlls:

![grafik](https://github.com/vvvv/VL.Audio.GPL/assets/3253299/35f6503c-087f-462a-a56f-99fa872d9c5d)

**Comment by mhusinsky** [comment]
BTRack works again when manually referencing the dll as an additional existing DLL. the question is - is this meant to be done like this?

**Comment by joreg** [comment]
thanks for the pointer. turns out BTrackCLI.dll was mistakenly added as a native .dll. fixet in 1.2.0-preview
